# Generated by Django 4.1.1 on 2022-11-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='product',
            name='interested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='interested_in',
            field=models.ManyToManyField(related_name='clients', to='myapp.category'),
        ),
    ]
